server:
  port: 9090

spring:
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1024Mb
  #配置redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0 #默认是索引为的0的数据库

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.sun.jojo.controller: 'on'








