#通用环境配置
server:
  port: 9098

spring:
  #激活Profile配置
  profiles:
    active: dev
  #http配置
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1024Mb
  #配置redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0 #默认是索引为的0的数据库
  #数据源配置
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.20.10.6:3306/user?characterEncoding=utf8&useSSL=false
      username: root
      password: 19910902
  #视图模版引擎配置
  thymeleaf:
    #在构建URL时添加到视图名称前的前缀
    prefix: classpath:/templates/
    #在构建URL时添加到视图名称后的后缀
    suffix: .html
    cache: false
  #jpa配置
  jpa:
    show-sql: true
    hibernate:
      #可以根据实体自动创建表
      ddl-auto: update


logging:
  level:
    com.sun.jojo.controller: 'on'


autoconfigtest:
  msg: 'jojo'







